### ISSUE TITLE
Firebase error when running from source on Windows

### ISSUE THREAD

**Issue by Sertelegger** [Cinq-Mars-Media/The-Devils-Calculator-A-Math-Puzzle-Game#1]
When running the sources with `npm run start` on Windows I ended up getting a Firebase error in the hosted website due to `databaseUrl` not being set. Turns out that's because the `options` parameter passed into Firebase isn't populated.

**Comment by ccj242** [comment]
Hey @Sertelegger, I sent you a DM on twitter, looking forward to chatting about this!
